### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by brendanfalkowski** [ryanstreet/magento2-vagrant#1]
Continuing onward from here: https://github.com/alankent/vagrant-magento2-apache-base/issues/5

Tried this setup, and got a roadblock almost immediately:

```
brendan$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The following settings shouldn't exist: post_up_message
```

After upgrading Vagrant from 1.5.3 to 1.7.2 I was able to get past it to the Magento setup screen.

But then got stuck on step 2:

![screen shot 2015-01-08 at 12 47 17 am](https://cloud.githubusercontent.com/assets/214924/5658459/f391362a-96cf-11e4-8d3b-2c6b596d46e0.png)

**Comment by brendanfalkowski** [comment]
FYI — for my own reference — when vagrant is up, you can get to this page via http://192.168.33.10/magento2/setup/

**Comment by ryanstreet** [comment]
I will update the README of the URL.  I will also put in minimum requirements in the Vagrant file.  Thank you for the feedback!

**Comment by ryanstreet** [comment]
I have updated database name to "magento" instead of "magento2".  Moved Post Up message to boostrap file, (removing Vagrant minimum requirements).

**Comment by brendanfalkowski** [comment]
Rebuilt my VM:

```
vagrant destroy
git pull
vagrant up
```

Got through install this time (yesss). But loading the site hits an error:

```
SQLSTATE[28000] [1045] Access denied for user 'magento'@'localhost' (using password: YES)
#0 /Users/brendan/work/playground/magento2/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(315): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 /Users/brendan/work/playground/magento2/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(460): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect()
#3 /Users/brendan/work/playground/magento2/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET NAMES utf8;', Array)
#4 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(416): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8;', Array)
#5 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/Model/Resource/Type/Db/Pdo/Mysql.php(59): Magento\Framework\DB\Adapter\Pdo\Mysql->query('SET NAMES utf8;')
#6 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/Model/Resource/Type/Db/ConnectionFactory.php(42): Magento\Framework\Model\Resource\Type\Db\Pdo\Mysql->getConnection(Object(Magento\Framework\DB\Logger\Null))
#7 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/App/Resource/ConnectionFactory.php(23): Magento\Framework\Model\Resource\Type\Db\ConnectionFactory->create(Array)
#8 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/App/Resource.php(103): Magento\Framework\App\Resource\ConnectionFactory->create(Array)
#9 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(278): Magento\Framework\App\Resource->getConnection('core_write')
#10 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(308): Magento\Framework\Model\Resource\Db\AbstractDb->_getConnection('write')
#11 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(293): Magento\Framework\Model\Resource\Db\AbstractDb->_getWriteAdapter()
#12 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(318): Magento\Framework\Model\Resource\Db\AbstractDb->_getReadAdapter()
#13 /Users/brendan/work/playground/magento2/magento2/var/generation/Magento/Store/Model/Resource/Website/Interceptor.php(182): Magento\Framework\Model\Resource\Db\AbstractDb->getReadConnection()
#14 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/Model/Resource/Db/Collection/AbstractCollection.php(116): Magento\Store\Model\Resource\Website\Interceptor->getReadConnection()
#15 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(104): Magento\Framework\Model\Resource\Db\Collection\AbstractCollection->__construct(Object(Magento\Core\Model\EntityFactory), Object(Magento\Framework\Logger\Monolog), Object(Magento\Framework\Data\Collection\Db\FetchStrategy\Cache), Object(Magento\Framework\Event\Manager\Proxy), NULL, NULL)
#16 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(90): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Store\M...', Array)
#17 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(55): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Store\M...', Array)
#18 /Users/brendan/work/playground/magento2/magento2/var/generation/Magento/Store/Model/Resource/Website/CollectionFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Store\M...', Array)
#19 /Users/brendan/work/playground/magento2/magento2/app/code/Magento/Store/Model/Storage/Db.php(191): Magento\Store\Model\Resource\Website\CollectionFactory->create()
#20 /Users/brendan/work/playground/magento2/magento2/app/code/Magento/Store/Model/Storage/Db.php(458): Magento\Store\Model\Storage\Db->_initStores()
#21 /Users/brendan/work/playground/magento2/magento2/app/code/Magento/Store/Model/StorageFactory.php(138): Magento\Store\Model\Storage\Db->reinitStores()
#22 /Users/brendan/work/playground/magento2/magento2/app/code/Magento/Store/Model/StorageFactory.php(113): Magento\Store\Model\StorageFactory->_reinitStores(Object(Magento\Store\Model\Storage\Db), Array)
#23 /Users/brendan/work/playground/magento2/magento2/app/code/Magento/Store/Model/StoreManager.php(120): Magento\Store\Model\StorageFactory->get(Array)
#24 /Users/brendan/work/playground/magento2/magento2/app/code/Magento/Store/Model/StoreManager.php(186): Magento\Store\Model\StoreManager->_getStorage()
#25 /Users/brendan/work/playground/magento2/magento2/app/code/Magento/Store/App/Request/PathInfoProcessor.php(34): Magento\Store\Model\StoreManager->getStores(false, true)
#26 /Users/brendan/work/playground/magento2/magento2/var/generation/Magento/Store/App/Request/PathInfoProcessor/Proxy.php(95): Magento\Store\App\Request\PathInfoProcessor->process(Object(Magento\Framework\App\Request\Http), '/')
#27 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/App/Request/Http.php(165): Magento\Store\App\Request\PathInfoProcessor\Proxy->process(Object(Magento\Framework\App\Request\Http), '/')
#28 /Users/brendan/work/playground/magento2/magento2/vendor/magento/zendframework1/library/Zend/Controller/Request/Http.php(662): Magento\Framework\App\Request\Http->setPathInfo()
#29 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/App/Request/Http.php(266): Zend_Controller_Request_Http->getPathInfo()
#30 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/App/Http.php(109): Magento\Framework\App\Request\Http->getFrontName()
#31 /Users/brendan/work/playground/magento2/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(244): Magento\Framework\App\Http->launch()
#32 /Users/brendan/work/playground/magento2/magento2/index.php(38): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#33 {main}
```

**Comment by ryanstreet** [comment]
Issue with locales and MySQL 5.6.  Fixed with latest release.
